LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := \
        cscrypt/aes.c \
        cscrypt/bn_add.c \
        cscrypt/bn_asm.c \
        cscrypt/bn_ctx.c \
        cscrypt/bn_div.c \
        cscrypt/bn_exp.c \
        cscrypt/bn_lib.c \
        cscrypt/bn_mul.c \
        cscrypt/bn_print.c \
        cscrypt/bn_shift.c \
        cscrypt/bn_sqr.c \
        cscrypt/bn_word.c \
        cscrypt/mem.c \
        cscrypt/des.c \
        cscrypt/i_cbc.c \
        cscrypt/i_ecb.c \
        cscrypt/i_skey.c \
        cscrypt/md5.c \
        cscrypt/rc6.c \
        cscrypt/sha1.c \
        csctapi/atr.c \
        csctapi/icc_async.c \
        csctapi/io_serial.c \
        csctapi/protocol_t0.c \
        csctapi/protocol_t1.c \
        csctapi/ifd_azbox.c \
        csctapi/ifd_cool.c \
        csctapi/ifd_cool.c \
        csctapi/ifd_db2com.c \
        csctapi/ifd_mp35.c \
        csctapi/ifd_pcsc.c \
        csctapi/ifd_phoenix.c \
        csctapi/ifd_sc8in1.c \
        csctapi/ifd_sci.c \
        csctapi/ifd_smargo.c \
        csctapi/ifd_smartreader.c \
        csctapi/ifd_stinger.c \
        csctapi/ifd_stapi.c \
        csctapi/ifd_stapi.c \
        minilzo/minilzo.c \
        module-anticasc.c \
        module-cacheex.c \
        module-camd33.c \
        module-camd35-cacheex.c \
        module-camd35.c \
        module-cccam-cacheex.c \
        module-cccam.c \
        module-cccshare.c \
        module-constcw.c \
        module-csp.c \
        module-cw-cycle-check.c \
        module-dvbapi-azbox.c \
        module-dvbapi-mca.c \
        module-dvbapi-coolapi.c \
        module-dvbapi-coolapi.c \
        module-dvbapi-coolapi.c \
        module-dvbapi-stapi.c \
        module-dvbapi-stapi5.c \
        module-dvbapi-chancache.c \
        module-dvbapi.c \
        module-gbox-helper.c \
        module-gbox-sms.c \
        module-gbox-cards.c \
        module-gbox.c \
        module-ird-guess.c \
        module-lcd.c \
        module-led.c \
        module-monitor.c \
        module-newcamd.c \
        module-newcamd-des.c \
        module-pandora.c \
        module-ghttp.c \
        module-radegast.c \
        module-scam.c \
        module-serial.c \
        module-stat.c \
        module-webif-lib.c \
        module-webif-tpl.c \
        module-webif.c \
        webif/pages.c \
        reader-common.c \
        reader-bulcrypt.c \
        reader-conax.c \
        reader-cryptoworks.c \
        reader-dgcrypt.c \
        reader-dre.c \
        reader-griffin.c \
        reader-irdeto.c \
        reader-nagra.c \
        reader-seca.c \
        reader-tongfang.c \
        reader-viaccess.c \
        reader-videoguard-common.c \
        reader-videoguard1.c \
        reader-videoguard12.c \
        reader-videoguard2.c \
        oscam-aes.c \
        oscam-array.c \
        oscam-hashtable.c \
        oscam-cache.c \
        oscam-chk.c \
        oscam-client.c \
        oscam-conf.c \
        oscam-conf-chk.c \
        oscam-conf-mk.c \
        oscam-config-account.c \
        oscam-config-global.c \
        oscam-config-reader.c \
        oscam-config.c \
        oscam-ecm.c \
        oscam-emm.c \
        oscam-emm-cache.c \
        oscam-failban.c \
        oscam-files.c \
        oscam-garbage.c \
        oscam-lock.c \
        oscam-log.c \
        oscam-log-reader.c \
        oscam-net.c \
        oscam-llist.c \
        oscam-reader.c \
        oscam-simples.c \
        oscam-string.c \
        oscam-time.c \
        oscam-work.c \
        oscam.c \
        config.c \

LOCAL_CFLAGS +=  -Wno-pointer-bool-conversion -Wno-date-time

LOCAL_MODULE := oscam
LOCAL_MODULE_TAGS := optional
LOCAL_SHARED_LIBRARIES := libssl libcrypto

include $(BUILD_EXECUTABLE)
